sonar.projectKey=dev-ia-auth
sonar.projectName=DEV IA - Autenticacao

sonar.sources=.
sonar.tests=.

sonar.test.inclusions=test_*.py,**/test_*.py
sonar.exclusions=test_*.py,**/test_*.py,.venv/**,**/__pycache__/**,instance/**,**/*.db,.pytest_cache/**,.git/**,.scannerwork/**

sonar.sourceEncoding=UTF-8
sonar.python.version=3